  name: pipline-api


  on:
    push:
      branches:
        - master
      paths:
        - 'hotel-api/**'
        - 'documentation/**'
    pull_request:
      branches:
        - master
        - develop
      paths:
        - 'hotel-api/**'
    workflow_dispatch:
  
  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Set up SSH
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H 89.168.20.112 >> ~/.ssh/known_hosts
    
        - name: Archive project files
          run: tar -czf app.tar.gz ./hotel-api
  
        - name: Copy archive to server
          run: scp -i ~/.ssh/id_rsa  app.tar.gz hamza@89.168.20.112:/home/hamza/
  
        - name: Deploy with Docker Compose
          run: |
            ssh -i ~/.ssh/id_rsa  hamza@89.168.20.112 << 'EOF'
              cd /home/hamza
              
              # Installer Docker Compose 
              if ! command -v docker-compose &> /dev/null; then
                echo "Bandello31!!!" | sudo -S apt update
                echo "Bandello31!!!" | sudo -S apt install -y docker-compose
              fi
              
              rm -rf hotel-api
              tar -xzf app.tar.gz 
              cd hotel-api
              echo "Bandello31!!!" | sudo -S echo "Bandello31!!!" | -S  docker-compose down
              echo "Bandello31!!!" | sudo -S docker image rm web-traficandme_frontend
              echo "Bandello31!!!" | sudo -S docker-compose up -d
            EOF
