name: Pipeline-Web

on:
  push:
    branches:
      - master
    paths:
      - 'hotel-web/**'
      - '.github/workflows/pipline-web.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'hotel-web/**'
      - '.github/workflows/pipline-web.yml'
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./hotel-web

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: './hotel-web/package-lock.json'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint -- --max-warnings=0 || true

      - name: Run Test
        run: npm test

      - name: Run App for Cypress
        run: npm run dev
        
      - name: Run Cypress
        run: npm run cypress:run

  security:
    needs: test
    # Only run on push to master or manual trigger, not on pull requests
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./hotel-web

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit

      - name: Check for outdated packages
        run: npm outdated || true

  build:
    needs: security
    # Only run on push to master or manual trigger, not on pull requests
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./hotel-web

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: './hotel-web/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build || true

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: hotel-web/dist

  deploy:
    needs: build
    # Only run on push to master or manual trigger, not on pull requests
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ./dist

      - name: Deploy to Production
        run: |
          echo "Deploying to production..."
          echo "Frontend deployment would happen here"
          echo "Deployment completed successfully!"
